---
title: "tenniscleaning"
author: "Nicholas Tating"
date: "4/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
AusMen <- read.csv(file = "AusOpen-men-2013.csv", stringsAsFactors = F)
AusWom <- read.csv(file = "AusOpen-women-2013.csv", stringsAsFactors = F)
FreMen <- read.csv(file = "FrenchOpen-men-2013.csv", stringsAsFactors = F)
FreWom <- read.csv(file = "FrenchOpen-women-2013.csv", stringsAsFactors = F)
USMen <- read.csv(file = "USOpen-men-2013.csv", stringsAsFactors = F)
USWom <- read.csv(file = "USOpen-women-2013.csv", stringsAsFactors = F)
WimMen <- read.csv(file = "Wimbledon-men-2013.csv", stringsAsFactors = F)
WimWom <- read.csv(file = "Wimbledon-women-2013.csv", stringsAsFactors = F)
```

```{r}
library(dplyr)
AusMen <- AusMen %>%
  mutate(Tournament = "AusMen")
AusWom <- AusWom %>%
  mutate(Tournament = "AusWom")
FreMen <- FreMen %>%
  mutate(Tournament = "FreMen")
FreWom <- FreWom %>%
  mutate(Tournament = "FreMen")
USMen <- USMen %>%
  mutate(Tournament = "USMen")
USWom <- USWom %>%
  mutate(Tournament = "USWom")
WimMen <- WimMen %>%
  mutate(Tournament = "WimMen")
WimWom <- WimWom %>%
  mutate(Tournament = "WimWom")
```

```{r}
columns <- names(AusMen)
names(AusWom) <- columns
names(FreMen) <- columns
names(FreWom) <- columns
names(USMen) <- columns
names(USWom) <- columns
names(WimMen) <- columns
names(WimWom) <- columns
```

```{r}
all_df <- rbind(AusMen,AusWom)
all_df <- rbind(all_df,FreMen)
all_df <- rbind(all_df,FreWom)
all_df <- rbind(all_df,USMen)
all_df <- rbind(all_df,USWom)
all_df <- rbind(all_df,WimMen)
all_df <- rbind(all_df,WimWom)
all_df
```

```{r}
write.csv(all_df, file = "tournament_data.csv")
```